# Generated by Django 5.2.11 on 2026-02-16 23:26

import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=16)),
                ('status', models.CharField(choices=[('active', 'active'), ('disabled', 'disabled')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('run_in', 'run_in'), ('active', 'active'), ('completed', 'completed')], default='draft', max_length=16)),
                ('lifecycle_state', models.CharField(choices=[('draft', 'draft'), ('running', 'running'), ('stopped', 'stopped')], default='draft', max_length=16)),
                ('baseline_locked', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration_weeks', models.IntegerField(default=0)),
                ('light_schedule', models.TextField(blank=True)),
                ('tent_notes', models.TextField(blank=True)),
                ('water_source', models.TextField(blank=True)),
                ('ventilation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_code', models.CharField(max_length=64)),
                ('volume_ml', models.IntegerField(blank=True, null=True)),
                ('ec_ms_cm', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('appearance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='api.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='MetricTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('category', 'version'), name='unique_metric_template_category_version')],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plant_id', models.CharField(blank=True, default='', max_length=64)),
                ('cultivar', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('removed', 'removed'), ('inactive', 'inactive'), ('dead', 'dead')], default='active', max_length=16)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_reason', models.TextField(blank=True)),
                ('baseline_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='api.experiment')),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='api.plant')),
            ],
        ),
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=128)),
                ('severity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('action_taken', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', to='api.experiment')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', to='api.plant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='api.experiment')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='assigned_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plants', to='api.recipe'),
        ),
        migrations.CreateModel(
            name='FeedingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('dose_value', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('dose_unit', models.CharField(choices=[('drops', 'drops'), ('ml', 'ml')], default='drops', max_length=16)),
                ('dosed_trap_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('fed', 'fed'), ('skipped', 'skipped'), ('paused', 'paused')], default='fed', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('amount_text', models.CharField(blank=True, max_length=64)),
                ('created_by_email', models.EmailField(blank=True, max_length=254)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_events', to='api.experiment')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_events', to='api.batchlot')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_events', to='api.plant')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_events', to='api.recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='batchlot',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='api.recipe'),
        ),
        migrations.CreateModel(
            name='ScheduleAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('FEED', 'Feed'), ('ROTATE', 'Rotate'), ('PHOTO', 'Photo'), ('METRICS', 'Metrics'), ('NOTE', 'Note'), ('CUSTOM', 'Custom')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_actions', to='api.experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('CUSTOM_DAYS_INTERVAL', 'Custom days interval')], max_length=24)),
                ('interval_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('timeframe', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], default='MORNING', max_length=16)),
                ('exact_time', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.scheduleaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('TENT', 'Tent'), ('TRAY', 'Tray'), ('PLANT', 'Plant')], max_length=16)),
                ('scope_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='api.scheduleaction')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='api.species'),
        ),
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, default='', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('layout', models.JSONField(blank=True, default=api.models.default_tent_layout)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_species', models.ManyToManyField(blank=True, related_name='tents', to='api.species')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tents', to='api.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shelf_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('slot_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('code', models.CharField(editable=False, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.tent')),
            ],
            options={
                'ordering': ['tent_id', 'shelf_index', 'slot_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tray',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('capacity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trays', to='api.experiment')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trays', to='api.slot')),
            ],
        ),
        migrations.CreateModel(
            name='RotationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('created_by_email', models.EmailField(blank=True, max_length=254)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_logs', to='api.experiment')),
                ('from_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_logs_from', to='api.slot')),
                ('to_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_logs_to', to='api.slot')),
                ('tray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_logs', to='api.tray')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('tag', models.CharField(choices=[('baseline', 'baseline'), ('weekly', 'weekly'), ('problem', 'problem'), ('other', 'other')], default='other', max_length=16)),
                ('file', models.FileField(upload_to='photos/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.experiment')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='api.plant')),
                ('tray', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='api.tray')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrayPlant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(default=0)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tray_plants', to='api.plant')),
                ('tray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tray_plants', to='api.tray')),
            ],
        ),
        migrations.AddField(
            model_name='tray',
            name='plants',
            field=models.ManyToManyField(related_name='trays', through='api.TrayPlant', to='api.plant'),
        ),
        migrations.CreateModel(
            name='WeeklySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('session_date', models.DateField()),
                ('checklist_state', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_sessions', to='api.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='PlantWeeklyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_weekly_metrics', to='api.experiment')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_metrics', to='api.plant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plant', 'week_number'), name='unique_plant_weekly_metric')],
            },
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('experiment', 'code'), name='unique_recipe_code_in_experiment'),
        ),
        migrations.AddConstraint(
            model_name='batchlot',
            constraint=models.UniqueConstraint(fields=('experiment', 'lot_code'), name='unique_lot_code_in_experiment'),
        ),
        migrations.AddConstraint(
            model_name='schedulescope',
            constraint=models.UniqueConstraint(fields=('schedule_action', 'scope_type', 'scope_id'), name='unique_schedule_scope_target'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('plant_id', ''), _negated=True), models.Q(('status', 'removed'), _negated=True)), fields=('experiment', 'plant_id'), name='unique_plant_id_in_experiment'),
        ),
        migrations.AddConstraint(
            model_name='tent',
            constraint=models.UniqueConstraint(fields=('experiment', 'name'), name='unique_tent_name_in_experiment'),
        ),
        migrations.AddConstraint(
            model_name='tent',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('experiment', 'code'), name='unique_tent_code_in_experiment'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('tent', 'shelf_index', 'slot_index'), name='unique_slot_coordinate_in_tent'),
        ),
        migrations.AddConstraint(
            model_name='trayplant',
            constraint=models.UniqueConstraint(fields=('tray', 'plant'), name='unique_plant_in_tray'),
        ),
        migrations.AddConstraint(
            model_name='trayplant',
            constraint=models.UniqueConstraint(fields=('plant',), name='unique_plant_single_tray'),
        ),
        migrations.AddConstraint(
            model_name='trayplant',
            constraint=models.UniqueConstraint(fields=('tray', 'order_index'), name='unique_tray_order_index'),
        ),
        migrations.AddConstraint(
            model_name='tray',
            constraint=models.UniqueConstraint(fields=('experiment', 'name'), name='unique_tray_name_in_experiment'),
        ),
        migrations.AddConstraint(
            model_name='tray',
            constraint=models.UniqueConstraint(fields=('slot',), name='unique_tray_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='weeklysession',
            constraint=models.UniqueConstraint(fields=('experiment', 'week_number'), name='unique_weekly_session'),
        ),
    ]
