# Generated by Django 5.2.11 on 2026-02-14 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_missing_setup_state(apps, schema_editor):
    Experiment = apps.get_model("api", "Experiment")
    ExperimentSetupState = apps.get_model("api", "ExperimentSetupState")
    for experiment in Experiment.objects.all():
        ExperimentSetupState.objects.get_or_create(experiment=experiment)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_experiment_species_block_batchlot_plant_adverseevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentSetupState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_packet', models.CharField(default='environment', max_length=32)),
                ('completed_packets', models.JSONField(blank=True, default=list)),
                ('locked_packets', models.JSONField(blank=True, default=list)),
                ('packet_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_state', to='api.experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_missing_setup_state, migrations.RunPython.noop),
    ]
