# Generated by Django 5.2.11 on 2026-02-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_experiment_lifecycle_state_experiment_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tray',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trays', to='api.block'),
        ),
        migrations.AddConstraint(
            model_name='trayplant',
            constraint=models.UniqueConstraint(fields=('plant',), name='unique_plant_single_tray'),
        ),
    ]
