# Generated by Django 5.2.11 on 2026-02-14 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tray_block_trayplant_unique_plant_single_tray'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rotationlog',
            name='unique_weekly_tray_rotation',
        ),
        migrations.RemoveField(
            model_name='rotationlog',
            name='block',
        ),
        migrations.RemoveField(
            model_name='rotationlog',
            name='rotated_at',
        ),
        migrations.RemoveField(
            model_name='rotationlog',
            name='week_number',
        ),
        migrations.AddField(
            model_name='rotationlog',
            name='created_by_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='rotationlog',
            name='from_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_logs_from', to='api.block'),
        ),
        migrations.AddField(
            model_name='rotationlog',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rotationlog',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rotationlog',
            name='to_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_logs_to', to='api.block'),
        ),
    ]
