# Generated by Django 5.2.11 on 2026-02-14 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_rotationlog_unique_weekly_tray_rotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingevent',
            name='amount_text',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='feedingevent',
            name='created_by_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='feedingevent',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedingevent',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedingevent',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_events', to='api.recipe'),
        ),
        migrations.AlterField(
            model_name='feedingevent',
            name='week_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
