# Generated by Django 5.2.11 on 2026-02-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_feedingevent_amount_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tray',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trays', to='api.recipe'),
        ),
    ]
