# Generated by Django 5.2.11 on 2026-02-14

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.db.models import Q


def create_default_tents_and_reparent_blocks(apps, schema_editor):
    Experiment = apps.get_model("api", "Experiment")
    Tent = apps.get_model("api", "Tent")
    Block = apps.get_model("api", "Block")

    for experiment in Experiment.objects.all().iterator():
        default_tent = Tent.objects.filter(experiment=experiment).order_by("id").first()
        if default_tent is None:
            default_tent = Tent.objects.create(
                experiment=experiment,
                name="Tent 1",
                code="T1",
            )

        Block.objects.filter(experiment=experiment, tent__isnull=True).update(tent=default_tent)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_tray_recipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(blank=True, default="", max_length=16)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tents",
                        to="api.experiment",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="tray",
            old_name="recipe",
            new_name="assigned_recipe",
        ),
        migrations.AddField(
            model_name="block",
            name="tent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="api.tent",
            ),
        ),
        migrations.AddConstraint(
            model_name="tent",
            constraint=models.UniqueConstraint(
                fields=("experiment", "name"),
                name="unique_tent_name_in_experiment",
            ),
        ),
        migrations.AddConstraint(
            model_name="tent",
            constraint=models.UniqueConstraint(
                condition=~Q(code=""),
                fields=("experiment", "code"),
                name="unique_tent_code_in_experiment",
            ),
        ),
        migrations.RunPython(create_default_tents_and_reparent_blocks, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="block",
            name="unique_block_name_in_experiment",
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.UniqueConstraint(
                fields=("tent", "name"),
                name="unique_block_name_in_tent",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="tent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="api.tent",
            ),
        ),
        migrations.AddField(
            model_name="tent",
            name="allowed_species",
            field=models.ManyToManyField(blank=True, related_name="tents", to="api.species"),
        ),
    ]
