# Generated by Django 5.2.11 on 2026-02-14 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tent_block_tent_and_tray_assigned_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tray',
            name='capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
