# Generated by Django 5.2.11 on 2026-02-14 13:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tray_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('FEED', 'Feed'), ('ROTATE', 'Rotate'), ('PHOTO', 'Photo'), ('METRICS', 'Metrics'), ('NOTE', 'Note'), ('CUSTOM', 'Custom')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_actions', to='api.experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('CUSTOM_DAYS_INTERVAL', 'Custom days interval')], max_length=24)),
                ('interval_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('timeframe', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], default='MORNING', max_length=16)),
                ('exact_time', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.scheduleaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('TENT', 'Tent'), ('TRAY', 'Tray'), ('PLANT', 'Plant')], max_length=16)),
                ('scope_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='api.scheduleaction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule_action', 'scope_type', 'scope_id'), name='unique_schedule_scope_target')],
            },
        ),
    ]
